#!/bin/bash

BASE_DIR=$(git rev-parse --show-toplevel)

if [ $? -ne 0 ] ; then
    echo "Not a git repository. Exiting now..."
    exit 21
fi

GITHOOK_DIR="${BASE_DIR}/githooks"

if [ -d "${GITHOOK_DIR}" ] ; then
    rm -rf "${GITHOOK_DIR}"
fi

if [ ! -z "$(which unzip)" ] ; then
    echo 'Starting unzip...'
    curl -fssL -o /tmp/master.zip https://github.com/huangsam/githooks/zipball/master
    unzip -q /tmp/master.zip -d /tmp && mv /tmp/huangsam-githooks* "${GITHOOK_DIR}"
elif [ ! -z "$(which tar)" ] ; then
    echo 'Starting tar...'
    curl -fssL -o /tmp/master.tar.gz https://github.com/huangsam/githooks/tarball/master
    tar -xf /tmp/master.tar.gz -C /tmp && mv /tmp/huangsam-githooks* "${GITHOOK_DIR}"
elif [ ! -z "$(which git)" ] ; then
    echo 'Starting git...'
    git clone -q https://github.com/huangsam/githooks.git "${GITHOOK_DIR}"
else
    echo 'unzip, tar and git do not exist. Exiting now...'
    exit 22
fi

echo 'Installing githooks...'
bash "${GITHOOK_DIR}/install.sh"
echo 'Removing githooks directory...'
rm -rf "${GITHOOK_DIR}"
rm -f /tmp/master.*
echo 'Installation successful. Exiting now...'
