#!/bin/bash
set -eu

BASE_DIR=$(git rev-parse --show-toplevel 2> /dev/null)

PIP_URL='https://github.com/huangsam/githooks/tarball/main'

echo 'Installing githooks package...'
pip install -q "$PIP_URL"

GIT_DIR="$BASE_DIR/.git"
GITHOOK_DIR="$GIT_DIR/githooks"
BUNDLE_DIR="$GITHOOK_DIR/bundle"

if [ -d "$GITHOOK_DIR" ] ; then
    echo "Wiping out old copy of $GITHOOK_DIR..."
    rm -rf "$GITHOOK_DIR"
else
    echo "Creating new copy of $GITHOOK_DIR..."
fi

if [ ! -z "$(which unzip)" ] ; then
    echo 'Attempting unzip...'
    curl -fssL -o /tmp/main.zip https://github.com/huangsam/githooks/zipball/main
    unzip -q /tmp/main.zip -d /tmp
    mv /tmp/huangsam-githooks* "$GITHOOK_DIR"
elif [ ! -z "$(which tar)" ] ; then
    echo 'Attempting tar...'
    curl -fssL -o /tmp/main.tar.gz https://github.com/huangsam/githooks/tarball/main
    tar -xf /tmp/main.tar.gz -C /tmp
    mv /tmp/huangsam-githooks* "$GITHOOK_DIR"
elif [ ! -z "$(which git)" ] ; then
    echo 'Attempting git...'
    git clone -q https://github.com/huangsam/githooks.git "$GITHOOK_DIR"
else
    echo 'unzip, tar and git do not exist. Exiting now...'
    exit 22
fi

echo "Removing git metadata from $GITHOOK_DIR..."
rm -rf "$GITHOOK_DIR/.git"

pushd "$GIT_DIR" &> /dev/null
echo 'Configuring hooks scripts...'
find "$BUNDLE_DIR" -name '*.py' -print0 | while read -d $'\0' fl ; do
    chmod +x "$fl"
    mv "$fl" "${fl%.py}"
done
echo 'Installing hooks scripts...'
rm -rf hooks
ln -s "$BUNDLE_DIR" hooks
popd &> /dev/null

echo 'Installation successful. Exiting now...'
