#!/bin/bash

BASE_DIR=$(git rev-parse --show-toplevel 2> /dev/null)

if [ $? -ne 0 ] ; then
    echo 'Not a git repository. Exiting now...'
    exit 21
else
    echo 'Proceeding with git repository.'
fi

GITHOOK_DIR="${BASE_DIR}/hooksimport"

if [ -d "${GITHOOK_DIR}" ] ; then
    rm -rf "${GITHOOK_DIR}"
fi

rm -rf /tmp/huangsam-githooks*

if [ ! -z "$(which unzip)" ] ; then
    echo 'Starting unzip...'
    curl -fssL -o /tmp/master.zip https://github.com/huangsam/githooks/zipball/master
    unzip -qo /tmp/master.zip -d /tmp && mv /tmp/huangsam-githooks* "${GITHOOK_DIR}"
elif [ ! -z "$(which tar)" ] ; then
    echo 'Starting tar...'
    curl -fssL -o /tmp/master.tar.gz https://github.com/huangsam/githooks/tarball/master
    tar -xf /tmp/master.tar.gz -C /tmp && mv /tmp/huangsam-githooks* "${GITHOOK_DIR}"
elif [ ! -z "$(which git)" ] ; then
    echo 'Starting git...'
    git clone -q https://github.com/huangsam/githooks.git "${GITHOOK_DIR}"
else
    echo 'unzip, tar and git do not exist. Exiting now...'
    exit 22
fi

echo 'Installation successful. Exiting now...'
