version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: python setup.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test:
          context: docker-hub-creds
